# Generated by Django 3.2.9 on 2022-02-08 17:28

from django.db import migrations


class Migration(migrations.Migration):
    def create_playbook(apps, schema_editor):
        playbook = apps.get_model('vulnApp', 'playbook')
        playbook.objects.create(category='Default', patchacquirement='Patch-Acquirement', patchvalidation='Patch-Validation', verification='Patch-Verification',rollout='Patch-Rollout', notes='')
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_playbook)
    ]
